name: ride_sharing
description: A Flutter Ride Sharing application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  firebase_database: ^4.3.0
  fluttertoast: ^7.1.1
  google_maps_flutter: ^1.2.0
  geolocator: ^6.1.14
  http: ^0.12.2
  provider: ^4.3.3
  flutter_polyline_points: ^0.2.4
  font_awesome_flutter: ^8.11.0
  flutter_geofire: ^1.0.3
  firebase_messaging: ^7.0.3
  maps_toolkit: ^1.1.0+2
  smooth_star_rating: ^1.1.1
  intl: ^0.16.0
  url_launcher: ^6.0.3
  cloud_firestore: ^0.14.1
  modal_progress_hud: ^0.1.3
  circular_countdown_timer: ^0.2.0
  square_in_app_payments: ^1.1.0
  image_picker: 0.6.7+8
  firebase_storage: ^5.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.4


flutter:

   uses-material-design: true

   assets:
     - images/



